---
repos:
  - repo: https://github.com/antonbabenko/pre-commit-terraform
    rev: v1.62.3
    hooks:
      - id: terraform_fmt

  - repo: https://github.com/terraform-docs/terraform-docs
    rev: v0.16.0
    hooks:
      - id: terraform-docs-system
        args: ['./']
      - id: terraform-docs-system
        args: ['./modules/aws_ec2']
      - id: terraform-docs-system
        args: ['./modules/aws_vpc']